name: Build zlib-ng

on:
  workflow_call:
    inputs:
      zlib_version:
        required: true
        type: string

jobs:
  build-zlib-dockcross:
    name: Build zlib
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler:
        - {target: windows-static-x86, src: z.dll, dst: zlib.dll, rid: win-x86}
        - {target: windows-static-x64, src: z.dll, dst: zlib.dll, rid: win-x64}
        - {target: linux-x64, src: libz.so, dst: zlib.so, rid: linux-x64}
        - {target: linux-armv6, src: libz.so, dst: zlib.so, rid: linux-arm}
        - {target: linux-arm64, src: libz.so, dst: zlib.so, rid: linux-arm64}
        - {target: "web-wasm:20241110-43b2dd1", src: libz.a, dst: zlib.a, rid: browser-wasm}

    container:
      image: dockcross/${{ matrix.compiler.target }}

    steps:
    - uses: actions/checkout@v4

    - name: Cache zlib-ng-${{ inputs.zlib_version }}
      id: cache-zlib
      uses: actions/cache@v4
      with:
        path: runtimes
        key: zlib-ng-${{ inputs.zlib_version }}-${{ matrix.compiler.rid }}

    - name: Download and extract zlib-ng-${{ inputs.zlib_version }}
      if: steps.cache-zlib.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/zlib-ng/zlib-ng/archive/refs/tags/${{ inputs.zlib_version }}.tar.gz
        tar -xzvf zlib-ng-${{ inputs.zlib_version }}.tar.gz

    - name: Build zlib-ng-${{ inputs.zlib_version }}
      if: steps.cache-zlib.outputs.cache-hit != 'true'
      run: |
        cmake -B build/${{ matrix.compiler.target }} -S zlib-${{ inputs.zlib_version }}/ -G Ninja -DZLIB_COMPAT=ON
        cmake --build . --config Release
        ctest --verbose -C Release
        mkdir -p runtimes/${{ matrix.compiler.rid }}/native
        cp build/${{ matrix.compiler.target }}/${{ matrix.compiler.src }} runtimes/${{ matrix.compiler.rid }}/native/${{ matrix.compiler.dst }}

    - name: Upload zlib-${{ inputs.zlib_version }}
      uses: actions/upload-artifact@v4
      with:
        name: zlib-${{ inputs.zlib_version }}-${{ matrix.compiler.rid }}
        path: runtimes
