name: Test zlib build

on:
  push:
    branches: [ "main", "dev" ]
    paths: [ ".github/workflows/ci.yml", "NativeSharpZlib/**", "NativeSharpZlib.Generators/**", "NativeSharpZlib.Tests/**", "NativeSharpZlib.sln" ]
  pull_request:
    branches: [ "main", "dev" ]
    paths: [ ".github/workflows/ci.yml", "NativeSharpZlib/**", "NativeSharpZlib.Generators/**", "NativeSharpZlib.Tests/**", "NativeSharpZlib.sln" ]

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build zlib ${{ vars.ZLIB_VERSION }} package
    uses: ./.github/workflows/build-zlib-package.yml
    with:
      zlib_version: ${{ vars.ZLIB_VERSION }}