name: CI

on:
  push:
    branches: [ "main", "dev" ]
    paths: [ ".github/workflows/*.yml", "NativeSharpZlib/**", "NativeSharpZlib.Generators/**", "NativeSharpZlib.Tests/**", "NativeSharpZlib.sln" ]
  pull_request:
    branches: [ "main", "dev" ]
    paths: [ ".github/workflows/*.yml", "NativeSharpZlib/**", "NativeSharpZlib.Generators/**", "NativeSharpZlib.Tests/**", "NativeSharpZlib.sln" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build zlib ${{ vars.ZLIB_VERSION }} package + test
    uses: ./.github/workflows/build-zlib-package.yml
    with:
      zlib_version: ${{ vars.ZLIB_VERSION }}
      runs-on: "['ubuntu-latest', 'windows-latest']"
