name: Test zlib build

on:
  workflow_dispatch:

env:
  ZLIB_VERSION: "1.2.5"

permissions:
  contents: read

jobs:
  compile-zlib-windows:
    name: Compile zlib on Windows
    runs-on: windows-latest

    steps:
    - name: Download zlib source
      run: |
        Invoke-WebRequest -Uri "https://www.zlib.net/fossils/zlib-${{ env.ZLIB_VERSION }}.tar.gz" -OutFile "zlib.tar.gz"
        tar -xzf zlib.tar.gz
        
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Configure and Build zlib
      run: |
        cd zlib-${{ env.ZLIB_VERSION }}
        ./configure
        make -f win32/Makefile.gcc

  compile-zlib-dockcross:
    name: Compile zlib (${{ matrix.compiler.rid }}) with Dockcross
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler:
          - {target: linux-x64, src: libz.so, dst: zlib.so, rid: linux-x64}
          - {target: linux-armv6, src: libz.so, dst: zlib.so, rid: linux-arm}
          - {target: linux-arm64, src: libz.so, dst: zlib.so, rid: linux-arm64}
          - {target: web-wasm, src: libz.a, dst: libz.a, rid: browser-wasm}
    
    container:
      image: dockcross/${{ matrix.compiler.target }}

    steps:
    - uses: actions/checkout@v4

    - name: Cache zlib-${{ env.ZLIB_VERSION }}
      id: cache-zlib
      uses: actions/cache@v4
      with:
        path: runtimes
        key: zlib-${{ env.ZLIB_VERSION }}-${{ matrix.compiler.rid }}

    - name: Download and extract zlib-${{ env.ZLIB_VERSION }}
      if: steps.cache-zlib.outputs.cache-hit != 'true'
      run: | 
        wget https://www.zlib.net/fossils/zlib-${{ env.ZLIB_VERSION }}.tar.gz
        tar -xzvf zlib-${{ env.ZLIB_VERSION }}.tar.gz
        rm zlib-${{ env.ZLIB_VERSION }}/zconf.h
    
    - name: Compile zlib-${{ env.ZLIB_VERSION }}
      if: steps.cache-zlib.outputs.cache-hit != 'true'
      run: |
        cmake -B build/${{ matrix.compiler.target }} -S zlib-${{ env.ZLIB_VERSION }}/ -G Ninja -DBUILD_SHARED_LIBS=ON
        ninja -C build/${{ matrix.compiler.target }} zlib
        mkdir -p runtimes/${{ matrix.compiler.rid }}/native
        cp build/${{ matrix.compiler.target }}/${{ matrix.compiler.src }} runtimes/${{ matrix.compiler.rid }}/native/${{ matrix.compiler.dst }}
        
    - name: Upload zlib-${{ env.ZLIB_VERSION }}
      uses: actions/upload-artifact@v4
      with:
        name: zlib-${{ env.ZLIB_VERSION }}-${{ matrix.compiler.rid }}
        path: runtimes
