name: Test zlib build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-zlib:
    uses: ./.github/workflows/build-zlib.yml
    with:
      zlib_version: 1.2.5

  build-and-test:
    needs: build-zlib

    name: Build and Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Download zlib build
      uses: actions/download-artifact@v4
      with:
        path: runtimes
        merge-multiple: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x
          8.0.x
          6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore -p:ContinuousIntegrationBuild=true -p:ZlibVersion=1.2.5

    - name: Copy native lib to test project (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cp -r runtimes/linux-x64/native/* NativeSharpZlib.Tests/bin/Release/net9.0
        cp -r runtimes/linux-x64/native/* NativeSharpZlib.Tests/bin/Release/net8.0
        cp -r runtimes/linux-x64/native/* NativeSharpZlib.Tests/bin/Release/net6.0

    - name: Copy native lib to test project (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        Copy-Item -Path 'runtimes/win-x64/native/*' -Destination 'NativeSharpZlib.Tests/bin/Release/net9.0' -Recurse
        Copy-Item -Path 'runtimes/win-x64/native/*' -Destination 'NativeSharpZlib.Tests/bin/Release/net8.0' -Recurse
        Copy-Item -Path 'runtimes/win-x64/native/*' -Destination 'NativeSharpZlib.Tests/bin/Release/net6.0' -Recurse

    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal --no-build --collect:"XPlat Code Coverage" --results-directory ./coverage